### ISSUE TITLE
cache.py raises exception but needs to log 

### ISSUE THREAD

**Issue by dclarke** [mozilla/appsync#6]
cache.py doesn't seem to be logging exceptions, might be good to put something in the log file

**Comment by tarekziade** [comment]
when CacheError() is raised, it bubbles up and then it's logged via a middleware that catches all errors, and return a 500.

That also creates a crash id for us to find the issue

see https://github.com/mozilla-services/mozservices/blob/master/mozsvc/middlewares.py#L128

**Comment by dclarke** [comment]
yup closing
